---
title: "AED Intro R Workshop Crib Sheet"
output: github_document
---

1. Welcome
2. Logistics
    - Schedule
    - Stickies
3. Introduction
    - Name
    - What I do
    - Branch
    - Motivation (why learn R)
4. **R BASICS**
5. R and RSTudio
    - Open RStudio
    - Walk Through layout
    - Create new project
    - Define a script
    - Create a ccript
6. *Exercise 1.1*
7. Workflow
    - Scripts vs. Console
9. Functions and Syntax
10. Other Stuff
    - #
    - ()
    - []
    - {}
11. Packages
    - What is a package
    - CRAN
    - Installation
    - Use a package
12. *Exercise 1.2*
13. Operators and Objects
    - +, -, *, ^, /, %%, >, <, >=, <=, !
    - <-
14. Managing objects and workspace
    - Command Line
    - RStudio Environment Window
    - RStudio tricks
15. Getting Help
    - From R:
        - When you know the command: ? or help()
        - When you know the package: help(package = "package")
        - When you know part of a name: ?? or apropos()
    - From R-Project:
        - R-help
        - R-sig-ecology
        - Task Views
    - The web:
        - Google
        - StackOverflow
    - Others:
        - R For Cats
        - Advanced R
16. **Data in R**
17. Atomic data types
    - character
    - numeric
    - logical
    - integer
    - complex 
    - raw
18. NA, NaN, Inf
19. Data Structures
    - vector
    - data.frame
    - list
    - matrix
    - factors
    - tables
20. Vectors
21. Data Frames
22. Factors
23. Lists
24. *Exercise 2.1*
25. Read External csv files
26. *Exercise 2.2*
27. Other ways to read data
    - readr
    - readxl
    - rio
    - DBI
    - RODBC
    - dplyr!
    - ...
28. 
